version: '3'
services:
  nginx:
   container_name: mynginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d

  mysql:
   container_name: mymysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: database
    MYSQL_ROOT_PASSWORD: password
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3306:3306"
   restart: always

  redis:
   container_name: myredis
   image: redis:3.2-alpine
   ports:
   - "6379:6379"
   restart: always

  app:
   container_name: app
   image: lucasferreira/baseapp
   restart: always
   #environment:
   #- JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005
   ports:
   - "5005:5005"
   - "8983:8983"
   expose:
   - "8080"
   depends_on:
   - nginx
   - mysql
   - redis